# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Forget me not
email: alberto.torres@icmat.es
description: Machine learning at ICMAT-CSIC
baseurl: 
url: https://albertotb.github.io
twitter_username:
github_username: albertotb
minimal_mistakes_skin: default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
#remote_theme: mmistakes/minimal-mistakes@4.15.1
#highlighter: rouge
#lsi: false
#excerpt_separator: "\n\n"
#incremental: false
#
#
## Markdown Processing
#kramdown:
#  input: GFM
#  hard_wrap: false
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  smart_quotes: lsquo,rsquo,ldquo,rdquo
#  enable_coderay: false

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alberto Torres Barrán"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Machine learning at ICMAT-CSIC"
  email  : "alberto.torres@icmat.es"
  location : "Madrid"
  github : "albertotb"
  linkdin: "albertotb"
  links :
    - label : "Linkdin"
      icon  : "fab fa-linkedin"
      url   : "https://www.linkedin.com/in/albertotb/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      clasess: wide
      author_profile: true
      read_time:
      comments:
      share: true
      related: true
